---
virtualmin_ip: 127.0.0.1
virtualmin_port: '10000'
virtualmin_user: root
virtualmin_password: bG92ZWFteTEzMTQ=\n
md5_key: days@net
access_server_ip:
- 211.102.90.30
- 211.102.90.36
- 127.0.0.1
- 192.168.1.111
- 192.168.1.99
